/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bcel.world.bug.poc;

import java.lang.reflect.InvocationTargetException;
import java.net.URISyntaxException;
import java.net.URL;

public class BcelWorldBugPoc {
    public static void main(String[] args) throws URISyntaxException, NoSuchFieldException, SecurityException, IllegalArgumentException, IllegalAccessException, NoSuchMethodException, InvocationTargetException {

		URL url = BcelWorldBugPoc.class.getClassLoader().getResource("bugged");
		
		AjCompiler ajCompiler = new AjCompiler(url.toURI().getPath());
		
		ajCompiler.compile();
    }
}
